# Generated by Django 5.2.3 on 2025-07-02 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meters_value', models.DecimalField(decimal_places=6, help_text='Input value in meters', max_digits=10)),
                ('feet_value', models.DecimalField(decimal_places=6, help_text='Converted value in feet', max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the conversion was performed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user (optional)', null=True)),
                ('user', models.ForeignKey(help_text='User who performed the conversion', on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversion',
                'verbose_name_plural': 'Conversions',
                'ordering': ['-timestamp'],
            },
        ),
    ]
